### ISSUE TITLE
Watchdog exception caused by AsyncHTTPSRequest_WT32_ETH01 example sketch

### ISSUE THREAD

**Issue by Oozlum** [khoih-prog/AsyncTCP_SSL#2]
### Describe the bug

Running the AsyncHTTPSRequest_WT32_ETH01 example sketch on a WT32-ETH01 board results in a watchdog exception which appears to be caused by AsyncTCP_SSL.

### Steps to Reproduce

Install Arduino IDE 1.8.19 and ESP32 Core 2.0.2.
Install the AsyncHTTPS_Generic library and dependencies.
Compile and run the example sketch.

### Expected behavior

The HTTPS request should complete successfully.

### Actual behavior

A watchdog exception is produced:

Starting AsyncHTTPSRequest_WT32_ETH01 using ESP32_DEV with ETH_PHY_LAN8720
WebServer_WT32_ETH01 v1.4.0 for core v2.0.0+
AsyncTCP_SSL v1.2.0
AsyncHTTPSRequest_Generic v2.0.0

ETH Started
ETH Connected
ETH MAC: 8C:CE:4E:95:15:CB, IPv4: 192.168.86.41
FULL_DUPLEX, 100Mbps

HTTP WebClient is @ IP : 192.168.86.41
E (7143) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (7143) task_wdt:  - async_tcp_ssl (CPU 0/1)
E (7143) task_wdt: Tasks currently running:
E (7143) task_wdt: CPU 0: IDLE
E (7143) task_wdt: CPU 1: loopTask
E (7143) task_wdt: Aborting.

abort() was called at PC 0x400e79fd on core 0

Backtrace:0x40083201:0x3ffbe9f00x4008ca2d:0x3ffbea10 0x40091b31:0x3ffbea30 0x400e79fd:0x3ffbeab0 0x40085949:0x3ffbead0 0x4015e32f:0x3ffbd8f0 0x400e8131:0x3ffbd910 0x4008df64:0x3ffbd930 

### Information

Please ensure to specify the following:

* Arduino IDE version 1.8.19
* ESP32 Core 2.0.2

**Comment by khoih-prog** [comment]
Hi @Oozlum 

Thanks for your interest in the library and your bug report.

I've tested and it's working OK here.

I suggest you check the installations, settings, etc. If  you can't solve the issue, ask for help in public forms, such as Arduino, ESP32, etc.

I'm closing the issue now because the invalid.

Good Luck,

---

### Terminal Debug Output

```
Starting AsyncHTTPSRequest_WT32_ETH01 using ESP32_DEV with ETH_PHY_LAN8720
WebServer_WT32_ETH01 v1.4.1 for core v2.0.0+
AsyncTCP_SSL v1.2.0
AsyncHTTPSRequest_Generic v2.0.0

ETH Started
ETH Connected
ETH MAC: A8:48:FA:08:4B:FF, IPv4: 192.168.2.97
FULL_DUPLEX, 100Mbps

HTTP WebClient is @ IP : 192.168.2.232

**************************************
abbreviation: EDT
client_ip: 45.72.131.83
datetime: 2022-03-22T13:06:12.885140-04:00
day_of_week: 2
day_of_year: 81
dst: true
dst_from: 2022-03-13T07:00:00+00:00
dst_offset: 3600
dst_until: 2022-11-06T06:00:00+00:00
raw_offset: -18000
timezone: America/Toronto
unixtime: 1647968772
utc_datetime: 2022-03-22T17:06:12.885140+00:00
utc_offset: -04:00
week_number: 12
**************************************
HHHHHH
**************************************
abbreviation: EDT
client_ip: 45.72.131.83
datetime: 2022-03-22T13:07:11.303113-04:00
day_of_week: 2
day_of_year: 81
dst: true
dst_from: 2022-03-13T07:00:00+00:00
dst_offset: 3600
dst_until: 2022-11-06T06:00:00+00:00
raw_offset: -18000
timezone: America/Toronto
unixtime: 1647968831
utc_datetime: 2022-03-22T17:07:11.303113+00:00
utc_offset: -04:00
week_number: 12
**************************************
```

**Comment by kardasis** [comment]
I'm having the same issue.  
@Oozlum did you figure anything out?
